services:

  express-server:
    container_name: express-server
    image: fgabler/express:latest
    build:
      context: ../.
      dockerfile: ./docker/express.Dockerfile
    volumes:
      - /var/local/data/leviForwardEmailSite/express-server/package.json:/app/package.json
    ports:
      - "3000:3000"
    networks:
      - express-and-nginx-net

  nginx:
    container_name: nginx
    image: fgabler/nginx:latest
    build:
      context: ../.
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "80"
    depends_on:
      - express-server
    volumes:
      - php-fpm-and-nginx-vol:/var/www/html
    networks:
      - express-and-nginx-net
      - php-fpm-and-nginx-net

  php-fpm:
    container_name: php-fpm
    image: fgabler/php-fpm:latest
    build:
      context: ../.
      dockerfile: ./docker/php_fpm.Dockerfile
    ports:
      - "9000"
    volumes:
      - php-fpm-and-nginx-vol:/var/www/html
    networks:
      - php-fpm-and-nginx-net

networks:
  express-and-nginx-net:
    name: express-and-nginx-net
    driver: bridge
  php-fpm-and-nginx-net:
    name: php-fpm-and-nginx-net
    driver: bridge

volumes:
  php-fpm-and-nginx-vol:
    name: "php-fpm-and-nginx-vol"
    driver: local
    driver_opts:
      device: "/var/local/data/leviForwardEmailSite/php-fpm-and-nginx"
      o: bind
      type: none
